// Sample data for browser testing
export const sampleData = [
  {
    "Program": "Vascular",
    "CPT Code": 35390,
    "Clinical Criteria": "Carotid endarterectomy is a procedure that involves making an incision into the internal carotid artery with surgical removal of atherosclerotic plaque and subsequent closure of the artery primarily or with a patch\n• CEA is considered medical necessary when one of the following is met\n    ◦ Symptomatic carotid stenosis-when there is documentation of both\n       ▪ Carotid lesion corresponds anatomically to the individual's symptoms or CTA or MRA findings in the distribution of carotid lesion and one of the following:\n           - 50-99% stenosis by angiogram, CTA, MRA\n           - Carotid duplex >70% (the lower value should be >70% if reported as a range) otherwise CTA or MRA needed to confirm\n       Documentation of any of the following\n           - Transient ischemic attack (TIA)\n           - Focal cerebral ischemia producing a non-disabling stroke\n           - Transient monocular blindness (amaurosis fugax)\n    ◦ Asymptomatic carotid stenosis (as documented by clinical notes):\n       ▪ Stenosis between 70%-99% on carotid duplex, CTA, MRA, or angiogram within last 6 months. Radiologist/Surgeons read using NASCET criteria must be documented for CTA/MRA/angiogram, providing an precise degree of stenosis\n",
    "Simplified Clinical Criteria": "Carotid endarterectomy is a surgery where a doctor opens a blood vessel in the neck to clean out stuff that is blocking the blood flow. After cleaning it, the doctor closes the blood vessel again.\n\nThis surgery is usually needed when one of the following is true:\n\n1. The person has symptoms that show the blood vessel is blocked, and tests prove it.\nThis means:\nThe blocked area in the neck matches the part of the brain where the symptoms are coming from.\nTests like scans or ultrasounds show the blood vessel is 50% to 99% blocked.\nAlso, the person must have had one of these:\n  - A mini-stroke that got better (called a TIA)\n  - A mild stroke that didn't cause serious lasting problems\n  - Temporary loss of vision in one eye\n2. The person has no symptoms, but a recent test (within 6 months) shows the blood vessel is badly blocked (70% to 99%).\nDoctors must clearly say how much the blood vessel is blocked, using special rules for reading the scan.\n",
    "Docs to Upload": "1) Clinical Notes\n2) X-ray report\n3) Imaging studies\n4) CAT Scan"
  },
  {
    "Program": "Vascular",
    "CPT Code": 37215,
    "Clinical Criteria": "Extracranial vertebral artery angioplasty with stent placement is considered medically necessary when all the following criteria are met:\n- Failure of antiplatelet therapy or anticoagulation therapy\n- One of the following recurrent symptoms after treatment of nonvascular etiologies:\n  - Dizziness\n  - Unilateral limb weakness\n  - Dysarthria\n  - Recurrent headache\n  - Recurrent nausea/vomiting\n  - Recurrent posterior circulation embolic stroke\n- One of the following criteria are met:\n  - 60-99% bilateral extracranial vertebral artery stenosis\n  - 60-99% unilateral extracranial vertebral artery stenosis in the setting of any of the following:\n- A dominant vertebral and hypoplastic contralateral vertebral\n- Contralateral vertebral ends in posteroinferior cerebellar\n- Contralateral vertebral is occluded",
    "Simplified Clinical Criteria": "Fixing a blocked neck artery with a small tube (stent) is needed when all of these are true:\n1) Medicines to stop blood clots didn't work.\n2) The person keeps having symptoms like:\n - Feeling dizzy\n - Weakness on one side of the body\n - Slurred speech\n - Headaches that keep coming back\n - Nausea or vomiting that comes back\n - A certain type of stroke that happens again\n3) And one of these is also true:\n    - Both neck arteries that go to the back of the brain are mostly blocked (60–99%)\n    - One neck artery is mostly blocked (60–99%) and:\n4) It's the main one doing the work because the other one is very small\n5) The other one stops before reaching the brain\n6) The other one is completely blocked",
    "Docs to Upload": "1) Clinical Notes\n2) X-ray report\n3) CAT Scan\n4) Blood test report"
  },
  {
    "Program": "Intravascular Ultrasound",
    "CPT Code": 37252,
    "Clinical Criteria": "The use of intravascular ultrasound is considered medically appropriate for the evaluation and treatment of:\n- Iliac vein or Inferior Vena Cava obstruction\n- Upper extremity venous obstruction\n- Superior Vena Cava Syndrome\n- Nutcracker Syndrome\n\nIVUS is indicated for use during a diagnostic procedure and again at the time of intervention for any of the following:\n- To diagnose or perform sizing measurements for urgent or elective thoracic aortic disease, if an approved indication is suspected\n- If requested to diagnose or perform sizing measurements for urgent or elective abdominal aortic disease, if an approved indication is suspected\n- Evaluation and treatment of iliac vein, abdominal or central Vena Cava obstruction\n- Appropriate for lower extremity PAD or peripheral aneurysm indication",
    "Simplified Clinical Criteria": "Using a special type of ultrasound that looks inside blood vessels is helpful and okay to use when checking or treating:\n - Blockages in large veins in the hip or belly\n - Blockages in veins in the arms\n - A condition where a big vein in the chest gets blocked\n - A condition where a vein near the kidney gets squeezed\n\nThis ultrasound can be used during tests and treatments for things like:\n - To check or measure problems in a big blood vessel in the chest, if there's a reason to think something is wrong\n - To check or measure problems in a big blood vessel in the belly, if there's a reason to think something is wrong\n - To check and help treat blockages in big veins in the belly or center of the body\n\nIt's also okay to use it to help with blood flow problems in the legs or swelling in certain blood vessels\n",
    "Docs to Upload": "1) Clinical Notes\n2) X-ray report\n3) CAT Scan\n4) UltraSound"
  },
  {
    "Program": "Intravascular Ultrasound",
    "CPT Code": 37253,
    "Clinical Criteria": "IVUS is indicated in the absence of pre-procedural imaging (such as MRA, CTA, or\nduplex ultrasound) in the evaluation of any of the following:\n• Aortic bifurcation and Iliac arteries (including Common Iliac artery, External Iliac artery\n  and Internal Iliac artery)\n    ◦ To minimize contrast in patients at increased risk for contrast related nephropathy\n    ◦ Confirm luminal placement of wire after crossing an occluded vessel segment\n    ◦ If there is concern for post intervention arterial dissection\n• Femoral- Popliteal Arteries\n    ◦ To minimize contrast in patients at increased risk for contrast related nephropathy\n    ◦ Ambiguous lesion or stenosis\n    ◦ Filling defect on angiography\n    ◦ Confirm luminal placement of wire after crossing an occluded vessel segment\n    ◦ If there is concern for post-intervention arterial dissection\n    ◦ Vessel sizing prior to use of Drug Coated Balloon or primary stenting 2,3,4 5\n        ▪ In the absence or pre-procedural imaging (such as MRA, CTA or duplex\n          ultrasound)\n    ◦ Determine appropriate therapeutic modality based on plaque morphology and\n      burden\n        ▪ In the absence or pre-procedural imaging (such as MRA, CTA or duplex\n          ultrasound)\r",
    "Simplified Clinical Criteria": "When to Use IVUS (a special kind of imaging inside blood vessels):\n\nIVUS can help when other pictures (like MRI, CT scan, or ultrasound) were not done before the procedure.\n\nFor blood vessels in the lower belly and hips:\n - To use less dye in people who might get kidney problems from the dye\n - To make sure a wire is in the right place after going through a blocked blood vessel\n - To check if the blood vessel is torn after a treatment\n\nFor blood vessels in the thigh and behind the knee:\n - To use less dye in people who might get kidney problems from the dye\n - When there is something unclear or unusual in the blood vessel\n - When an X-ray shows something might be blocking the blood flow\n - To make sure a wire is in the right place after going through a blocked blood vessel\n - To check if the blood vessel is torn after a treatment\n - To measure the size of the blood vessel before using certain balloons or stents\n      Only when no other pictures were taken before\n - To decide the best treatment based on how much and what kind of buildup is in the blood vessel\n      Only when no other pictures were taken before",
    "Docs to Upload": "1) Clinical Notes\n2) UltraSound"
  }
];